packages:
  - "__tests__"
  - "__tests__/*"
  - "packages/*"
  - "packages/$private/*"
  - "examples/**"
  - "!examples/**/.next/**"
  - "!examples/**/.output"
  - "serwist-e2e-test"
overrides:
  "@serwist/astro": "workspace:*"
  "@serwist/react-router": "workspace:*"
  "@serwist/window": "workspace:*"
  "serwist": "workspace:*"
  "vite-plugin-serwist": "workspace:*"
