packages:
  - "__tests__"
  - "__tests__/*"
  - "docs"
  - "packages/*"
  - "packages/$legacy/*"
  - "packages/$private/*"
  - "examples/**"
  - "!examples/**/.next/**"
  - "!examples/**/.output"
  - "serwist-e2e-test"
