packages:
  - "__tests__"
  - "__tests__/*"
  - "packages/*"
  - "packages/$legacy/*"
  - "packages/$private/*"
  - "examples/**"
  - "!examples/**/.next/**"
  - "!examples/**/.output"
  - "serwist-e2e-test"
overrides:
  "@serwist/astro": "workspace:*"
  "@serwist/cli": "workspace:*"
  "@serwist/react-router": "workspace:*"
  "@serwist/turbopack": "workspace:*"
  "@serwist/vite": "workspace:*"
  "@serwist/window": "workspace:*"
  "serwist": "workspace:*"