packages:
  - "__tests__"
  - "__tests__/*"
  - "__tests__/*/*"
  - "packages/*"
  - "packages/$legacy/*"
  - "packages/$private/*"
  - "examples/**"
  - "!examples/**/.next/**"
  - "!examples/**/.output"
  - "serwist-e2e-test"
overrides:
  "@serwist/astro": "workspace:*"
  "@serwist/cli": "workspace:*"
  "@serwist/react-router": "workspace:*"
  "@serwist/svelte": "workspace:*"
  "@serwist/turbopack": "workspace:*"
  "@serwist/vite": "workspace:*"
  "@serwist/window": "workspace:*"
  "serwist": "workspace:*"
minimumReleaseAge: 1440
shellEmulator: true
engineStrict: true
allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  core-js: true
  esbuild: true
  sharp: true
