name: Bug report
description: Create a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - DuCanhGH
body:
  - type: textarea
    attributes:
      label: Provide environment information
      description: Please provide the versions of relevant packages.
    validations:
      required: true
  - type: dropdown
    id: project
    attributes:
      multiple: false
      label: Which project is this issue for?
      options:
        - "serwist"
        - "@serwist/build"
        - "@serwist/cli"
        - "@serwist/next"
        - "@serwist/nuxt"
        - "@serwist/recipes"
        - "@serwist/streams"
        - "@serwist/svelte"
        - "vite-plugin-serwist"
        - "@serwist/webpack-plugin"
        - "@serwist/window"
  - type: input
    attributes:
      label: Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster
      description: A link to a GitHub repository, a StackBlitz, or a CodeSandbox. This reproduction should include only changes that contribute to the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior, please provide a clear description of how to reproduce the issue, based on the linked minimal reproduction. If you are using code blocks, make sure that [syntax highlighting is correct](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) and double check that the rendered preview is not broken.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Before posting the issue go through the steps you've written down to make sure the steps provided are detailed and clear.
  - type: textarea
    attributes:
      label: Screenshots (if relevant)
      description: Please also provide some screenshots if you can. Thanks!
  - type: textarea
    attributes:
      label: Additional information (if relevant)
      description: Please also provide some additional information about the issue if you can. Thanks!
