name: Feature request
description: Create a feature request
title: "[Feature request]: "
labels: ["feature request", "triage"]
assignees:
  - DuCanhGH
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a feature request! Please fill out this form as completely as possible.
  - type: markdown
    attributes:
      value: 'Feature requests will be converted to the GitHub Discussions "Ideas" section when suitable.'
  - type: dropdown
    id: project
    attributes:
      multiple: false
      label: Which project is this feature request for?
      options:
        - "@serwist/build"
        - "@serwist/cli"
        - "@serwist/core"
        - "@serwist/next"
        - "@serwist/recipes"
        - "@serwist/streams"
        - "@serwist/sw"
        - "@serwist/webpack-plugin"
        - "@serwist/window"
  - type: textarea
    attributes:
      label: Describe the feature you'd like to request
      description: A clear and concise description of what you want and what your use case is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
