export const COLOR_SCHEMES = ["dark", "light"] as const;

export const GITHUB_REPO_URL = "https://github.com/serwist/serwist";

export const REROUTE: Record<string, string> = {
  "/docs/next/configuring/additional-precache-entries": "/docs/build/configuring/additional-precache-entries",
  "/docs/next/configuring/chunks": "/docs/webpack-plugin/configuring/chunks",
  "/docs/next/configuring/compile-src": "/docs/webpack-plugin/configuring/compile-src",
  "/docs/next/configuring/dont-cache-bust-urls-matching": "/docs/build/configuring/dont-cache-bust-urls-matching",
  "/docs/next/configuring/exclude": "/docs/webpack-plugin/configuring/exclude",
  "/docs/next/configuring/exclude-chunks": "/docs/webpack-plugin/configuring/exclude-chunks",
  "/docs/next/configuring/include": "/docs/webpack-plugin/configuring/include",
  "/docs/next/configuring/injection-point": "/docs/build/configuring/injection-point",
  "/docs/next/configuring/manifest-transforms": "/docs/build/configuring/manifest-transforms",
  "/docs/next/configuring/maximum-file-size-to-cache-in-bytes": "/docs/build/configuring/maximum-file-size-to-cache-in-bytes",
  "/docs/next/configuring/modify-url-prefix": "/docs/build/configuring/modify-url-prefix",
  "/docs/next/configuring/sw-dest": "/docs/build/configuring/sw-dest",
  "/docs/next/configuring/sw-src": "/docs/build/configuring/sw-src",
  "/docs/next/configuring/webpack-compilation-plugins": "/docs/webpack-plugin/configuring/webpack-compilation-plugins",
  "/docs/nuxt/configuring/additional-precache-entries": "/docs/build/configuring/additional-precache-entries",
  "/docs/nuxt/configuring/base": "/docs/vite/configuring/base",
  "/docs/nuxt/configuring/dev-options": "/docs/vite/configuring/dev-options",
  "/docs/nuxt/configuring/disable": "/docs/vite/configuring/disable",
  "/docs/nuxt/configuring/dont-cache-bust-urls-matching": "/docs/build/configuring/dont-cache-bust-urls-matching",
  "/docs/nuxt/configuring/glob-directory": "/docs/build/configuring/glob-directory",
  "/docs/nuxt/configuring/glob-follow": "/docs/build/configuring/glob-follow",
  "/docs/nuxt/configuring/glob-ignores": "/docs/build/configuring/glob-ignores",
  "/docs/nuxt/configuring/glob-patterns": "/docs/build/configuring/glob-patterns",
  "/docs/nuxt/configuring/glob-strict": "/docs/build/configuring/glob-strict",
  "/docs/nuxt/configuring/injection-point": "/docs/build/configuring/injection-point",
  "/docs/nuxt/configuring/integration": "/docs/vite/configuring/integration",
  "/docs/nuxt/configuring/manifest-transforms": "/docs/build/configuring/manifest-transforms",
  "/docs/nuxt/configuring/maximum-file-size-to-cache-in-bytes": "/docs/build/configuring/maximum-file-size-to-cache-in-bytes",
  "/docs/nuxt/configuring/mode": "/docs/vite/configuring/mode",
  "/docs/nuxt/configuring/modify-url-prefix": "/docs/build/configuring/modify-url-prefix",
  "/docs/nuxt/configuring/plugins": "/docs/vite/configuring/plugins",
  "/docs/nuxt/configuring/rollup-format": "/docs/vite/configuring/rollup-format",
  "/docs/nuxt/configuring/rollup-options": "/docs/vite/configuring/rollup-options",
  "/docs/nuxt/configuring/scope": "/docs/vite/configuring/scope",
  "/docs/nuxt/configuring/sw-dest": "/docs/build/configuring/sw-dest",
  "/docs/nuxt/configuring/sw-src": "/docs/build/configuring/sw-src",
  "/docs/nuxt/configuring/sw-url": "/docs/vite/configuring/sw-url",
  "/docs/nuxt/configuring/templated-urls": "/docs/build/configuring/templated-urls",
  "/docs/nuxt/configuring/type": "/docs/vite/configuring/type",
  "/docs/vite/configuring/additional-precache-entries": "/docs/build/configuring/additional-precache-entries",
  "/docs/vite/configuring/dont-cache-bust-urls-matching": "/docs/build/configuring/dont-cache-bust-urls-matching",
  "/docs/vite/configuring/glob-directory": "/docs/build/configuring/glob-directory",
  "/docs/vite/configuring/glob-follow": "/docs/build/configuring/glob-follow",
  "/docs/vite/configuring/glob-ignores": "/docs/build/configuring/glob-ignores",
  "/docs/vite/configuring/glob-patterns": "/docs/build/configuring/glob-patterns",
  "/docs/vite/configuring/glob-strict": "/docs/build/configuring/glob-strict",
  "/docs/vite/configuring/injection-point": "/docs/build/configuring/injection-point",
  "/docs/vite/configuring/manifest-transforms": "/docs/build/configuring/manifest-transforms",
  "/docs/vite/configuring/maximum-file-size-to-cache-in-bytes": "/docs/build/configuring/maximum-file-size-to-cache-in-bytes",
  "/docs/vite/configuring/modify-url-prefix": "/docs/build/configuring/modify-url-prefix",
  "/docs/vite/configuring/sw-dest": "/docs/build/configuring/sw-dest",
  "/docs/vite/configuring/sw-src": "/docs/build/configuring/sw-src",
  "/docs/vite/configuring/templated-urls": "/docs/build/configuring/templated-urls",
  "/docs/webpack-plugin/configuring/additional-precache-entries": "/docs/build/configuring/additional-precache-entries",
  "/docs/webpack-plugin/configuring/disable-precache-manifest": "/docs/build/configuring/disable-precache-manifest",
  "/docs/webpack-plugin/configuring/dont-cache-bust-urls-matching": "/docs/build/configuring/dont-cache-bust-urls-matching",
  "/docs/webpack-plugin/configuring/injection-point": "/docs/build/configuring/injection-point",
  "/docs/webpack-plugin/configuring/manifest-transforms": "/docs/build/configuring/manifest-transforms",
  "/docs/webpack-plugin/configuring/maximum-file-size-to-cache-in-bytes": "/docs/build/configuring/maximum-file-size-to-cache-in-bytes",
  "/docs/webpack-plugin/configuring/modify-url-prefix": "/docs/build/configuring/modify-url-prefix",
  "/docs/webpack-plugin/configuring/sw-dest": "/docs/build/configuring/sw-dest",
  "/docs/webpack-plugin/configuring/sw-src": "/docs/build/configuring/sw-src",
};
